name: Deploy Backend (PHP via FTP)

on:
  push:
    branches:
      - main
    paths:
      - "admin/api/**"
      - "admin/config/**"
      - "assets/images/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          # Only upload backend-related files
          exclude: |
            **
            !admin/api/**
            !admin/config/**
            !assets/images/**
          dangerous-clean-slate: false
          # Keep timestamps to avoid unnecessary uploads
          state-name: .ftp-deploy-sync-state.json
